/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Payment;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import stokbarangpddj.ToolAndClass.Conn;
import stokbarangpddj.MenuUtama;
import stokbarangpddj.ToolAndClass.AllClass;
import stokbarangpddj.ToolAndClass.Tools;

/**
 *
 * @author Susanto
 */
public class PaymentManage extends javax.swing.JInternalFrame {

    /**
     * Creates new form PaymentManage
     */
    public PaymentManage() {
        initComponents();
        updatetab();
    }
    
    private void clear(){
        TXTNamePayment.setText("");
    }
    
    private void updatetab(){
                try {
                        DefaultTableModel Table = (DefaultTableModel) TabPayAndDisc.getModel();
                        while(Table.getRowCount() > 0) Table.removeRow(0);
			Conn.rowSet.setCommand("select * from payment");
			Conn.rowSet.execute();
			while(Conn.rowSet.next())
                        {
                            Table.addRow(new Object[]{Conn.rowSet.getString("idpayment"),Conn.rowSet.getString("Type_Payment")});
                        }
		} catch (SQLException ex) {
			Logger.getLogger(PaymentManage.class.getName()).log(Level.SEVERE, null, ex);
		}
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabPayAndDisc = new javax.swing.JTable();
        TXTNamePayment = new javax.swing.JTextField();
        AddBut = new javax.swing.JButton();
        UpdateBut = new javax.swing.JButton();
        DeleteBut = new javax.swing.JButton();
        BackBut = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(900, 597));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Payment", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel1.setText("Name Payment :");

        TabPayAndDisc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Type Payment"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabPayAndDisc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabPayAndDiscMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabPayAndDisc);
        if (TabPayAndDisc.getColumnModel().getColumnCount() > 0) {
            TabPayAndDisc.getColumnModel().getColumn(0).setPreferredWidth(30);
        }

        AddBut.setText("Add");
        AddBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButActionPerformed(evt);
            }
        });

        UpdateBut.setText("Update");
        UpdateBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButActionPerformed(evt);
            }
        });

        DeleteBut.setText("Delete");
        DeleteBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AddBut, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(UpdateBut, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DeleteBut, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TXTNamePayment, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TXTNamePayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddBut, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateBut, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteBut, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addContainerGap())
        );

        BackBut.setText("Back");
        BackBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(BackBut, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BackBut, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButActionPerformed
        MenuUtama MenuUtama = new MenuUtama();
        Tools.change(this, MenuUtama);
        // TODO add your handling code here:
    }//GEN-LAST:event_BackButActionPerformed

    private void AddButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButActionPerformed
    if(TXTNamePayment.getText().isEmpty() == true)
        {
            JOptionPane.showMessageDialog(null, "Your Data Is Not Complete!!","ERROR!!",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            try {
                    // TODO add your handling code here:
                    String GenerateID = AllClass.GenerateID("payment", "idpayment");
                    Conn.rowSet.setCommand("select * from payment");
                    Conn.rowSet.execute();
                    Conn.rowSet.moveToInsertRow();
                    Conn.rowSet.updateString("idpayment",GenerateID);
                    Conn.rowSet.updateString("Type_Payment", TXTNamePayment.getText());
                    Conn.rowSet.insertRow();
            } catch (SQLException ex) {
                    Logger.getLogger(PaymentManage.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "Please Correct Your Data!!", "Warning" ,JOptionPane.WARNING_MESSAGE);

            }
        }
        clear();
        updatetab();
        // TODO add your handling code here:
    }//GEN-LAST:event_AddButActionPerformed

    private void UpdateButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButActionPerformed
        if(TXTNamePayment.getText().isEmpty() == true)
        {
            JOptionPane.showMessageDialog(null, "Please Select Your Data First!!!!","ERROR!!",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            try {
                    // TODO add your handling code here:
                    int baris = TabPayAndDisc.getSelectedRow();
                    Conn.rowSet.setCommand("select * from payment");
                    Conn.rowSet.execute();
                    Conn.rowSet.absolute(baris+1);
                    Conn.rowSet.updateString("Type_Payment", TXTNamePayment.getText());
                    Conn.rowSet.updateRow();
                    updatetab();
                } catch (SQLException ex) {
                        Logger.getLogger(PaymentManage.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
        clear();
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateButActionPerformed

    private void DeleteButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButActionPerformed
        if(TXTNamePayment.getText().isEmpty() == true)
        {
            JOptionPane.showMessageDialog(null, "Please Select Your Data First!!!!","ERROR!!",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            try {
                    int baris = TabPayAndDisc.getSelectedRow();
                    Conn.rowSet.setCommand("select * from payment");
                    Conn.rowSet.execute();
                    Conn.rowSet.absolute(baris+1);
                    Conn.rowSet.deleteRow();
                    updatetab();
                } catch (SQLException ex) {
                        Logger.getLogger(PaymentManage.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
        clear();
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteButActionPerformed

    private void TabPayAndDiscMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabPayAndDiscMouseClicked
        int baris = TabPayAndDisc.getSelectedRow();
        TXTNamePayment.setText(TabPayAndDisc.getValueAt(baris, 1).toString());
        // TODO add your handling code here:
    }//GEN-LAST:event_TabPayAndDiscMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBut;
    private javax.swing.JButton BackBut;
    private javax.swing.JButton DeleteBut;
    private javax.swing.JTextField TXTNamePayment;
    private javax.swing.JTable TabPayAndDisc;
    private javax.swing.JButton UpdateBut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
