/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Store;

import UserAdmin.AdminUser;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import stokbarangpddj.ToolAndClass.Conn;
import stokbarangpddj.MenuUtama;
import stokbarangpddj.ToolAndClass.AllClass;
import stokbarangpddj.ToolAndClass.Tools;

/**
 *
 * @author Susanto
 */
public class Distributor extends javax.swing.JInternalFrame {

    /**
     * Creates new form Distributor
     */
    public Distributor() {
        initComponents();
        updateTable();
    }

    public void updateTable(){
		try {
                        DefaultTableModel Table = (DefaultTableModel) StoreTab.getModel();
                        while(Table.getRowCount() > 0) Table.removeRow(0);
			Conn.rowSet.setCommand("select iddistributor, Name, address, phone from distributor");
			Conn.rowSet.execute();
                        while(Conn.rowSet.next())
                        {
                            Table.addRow(new Object[]{Conn.rowSet.getString(1),Conn.rowSet.getString(2),Conn.rowSet.getString(3),Conn.rowSet.getString(4)});
                        }
		} catch (SQLException ex) {
			Logger.getLogger(AdminUser.class.getName()).log(Level.SEVERE, null, ex);
		}
    }
    
    private void clear(){
        TXTName.setText("");
        TXTAddress.setText("");
        TXTPhone.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        StoreTab = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TXTName = new javax.swing.JTextField();
        TXTPhone = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TXTAddress = new javax.swing.JTextArea();
        AddBut = new javax.swing.JButton();
        DeleteBut = new javax.swing.JButton();
        UpdateBut = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BackBut = new javax.swing.JButton();

        jLabel6.setText("jLabel6");

        setPreferredSize(new java.awt.Dimension(900, 597));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Distributor Form Registration", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        StoreTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Address", "Telephone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        StoreTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StoreTabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(StoreTab);

        jLabel1.setText("Name");

        jLabel2.setText("Address");

        jLabel3.setText("Phone");

        TXTPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TXTPhoneKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXTPhoneKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTPhoneKeyTyped(evt);
            }
        });

        TXTAddress.setColumns(20);
        TXTAddress.setRows(5);
        jScrollPane2.setViewportView(TXTAddress);

        AddBut.setText("Add");
        AddBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButActionPerformed(evt);
            }
        });

        DeleteBut.setText("Delete");
        DeleteBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButActionPerformed(evt);
            }
        });

        UpdateBut.setText("Update");
        UpdateBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButActionPerformed(evt);
            }
        });

        jLabel4.setText(":");

        jLabel5.setText(":");

        jLabel7.setText(":");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TXTName))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TXTPhone))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)))))
                        .addGap(13, 13, 13)
                        .addComponent(AddBut, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UpdateBut, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeleteBut, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TXTName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(AddBut, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateBut, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteBut, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TXTPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                .addContainerGap())
        );

        BackBut.setText("Back");
        BackBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BackBut, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BackBut, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButActionPerformed
        if(TXTName.getText().isEmpty() == true || TXTAddress.getText().isEmpty() == true || TXTPhone.getText().isEmpty() == true)
        {
            JOptionPane.showMessageDialog(null, "Your Data Is Not Complete!!");
        }
        else
        {
            try {
                String GenerateIDDist = AllClass.GenerateID("distributor", "iddistributor");
                // TODO add your handling code here:
                Conn.rowSet.setCommand("select * from distributor");
                Conn.rowSet.execute();
                Conn.rowSet.moveToInsertRow();
                Conn.rowSet.updateString("iddistributor", GenerateIDDist);
                Conn.rowSet.updateString("name", TXTName.getText());
                Conn.rowSet.updateString("address", TXTAddress.getText());
                Conn.rowSet.updateString("phone", TXTPhone.getText());
                Conn.rowSet.insertRow();
                updateTable();
            } catch (SQLException ex) {
                Logger.getLogger(AdminUser.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        clear();
        // TODO add your handling code here:
    }//GEN-LAST:event_AddButActionPerformed

    private void DeleteButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButActionPerformed
        if(TXTName.getText().isEmpty() == true || TXTAddress.getText().isEmpty() == true || TXTPhone.getText().isEmpty() == true)
        {
            JOptionPane.showMessageDialog(null, "Please Select Your Data First!!");
        }
        else
        {
            try {
                // TODO add your handling code here:
                Integer baris = StoreTab.getSelectedRow();
                Conn.rowSet.setCommand("select * from distributor");
                Conn.rowSet.execute();
                Conn.rowSet.absolute(baris+1);
                Conn.rowSet.deleteRow();
                updateTable();
            } catch (SQLException ex) {
                Logger.getLogger(AdminUser.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        clear();
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteButActionPerformed

    private void UpdateButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButActionPerformed
        if(TXTName.getText().isEmpty() == true || TXTAddress.getText().isEmpty() == true || TXTPhone.getText().isEmpty() == true)
        {
            JOptionPane.showMessageDialog(null, "Please Select Your Data First!!");
        }
        else
        {
            try {
                // TODO add your handling code here:
                Integer baris = StoreTab.getSelectedRow();
                Conn.rowSet.setCommand("select * from distributor");
                Conn.rowSet.execute();
                Conn.rowSet.absolute(baris+1);
                Conn.rowSet.updateString("name", TXTName.getText());
                Conn.rowSet.updateString("address", TXTAddress.getText());
                Conn.rowSet.updateString("phone", TXTPhone.getText());
                Conn.rowSet.updateRow();
                updateTable();
            } catch (SQLException ex) {
                Logger.getLogger(AdminUser.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        clear();
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateButActionPerformed

    private void TXTPhoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTPhoneKeyPressed

        // TODO add your handling code here:
    }//GEN-LAST:event_TXTPhoneKeyPressed

    private void StoreTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StoreTabMouseClicked
        Integer baris = StoreTab.getSelectedRow();
        TXTName.setText(StoreTab.getValueAt(baris, 1).toString());
        TXTAddress.setText(StoreTab.getValueAt(baris, 2).toString());
        TXTPhone.setText(StoreTab.getValueAt(baris, 3).toString());
        // TODO add your handling code here:
    }//GEN-LAST:event_StoreTabMouseClicked

    private void BackButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButActionPerformed
        MenuUtama MenuUtama = new MenuUtama();
        Tools.change(this, MenuUtama);
        // TODO add your handling code here:
    }//GEN-LAST:event_BackButActionPerformed

    private void TXTPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTPhoneKeyTyped
        // TODO add your handling code here:
    if(TXTPhone.getText().length()> 12)
    {
         JOptionPane.showMessageDialog(null, "Please Insert Correct Phone!! - Max 12");
         TXTPhone.setText("");
    }
    }//GEN-LAST:event_TXTPhoneKeyTyped

    private void TXTPhoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTPhoneKeyReleased
        // TODO add your handling code here:
    if(TXTPhone.getText().isEmpty() == false)
    {

        if(Tools.isNumeric(TXTPhone.getText())==false)
        {
            JOptionPane.showMessageDialog(null, "Not Valid Input!!","ERROR!!",JOptionPane.ERROR_MESSAGE);
            TXTPhone.setText("");
        }
    }
    }//GEN-LAST:event_TXTPhoneKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBut;
    private javax.swing.JButton BackBut;
    private javax.swing.JButton DeleteBut;
    private javax.swing.JTable StoreTab;
    private javax.swing.JTextArea TXTAddress;
    private javax.swing.JTextField TXTName;
    private javax.swing.JTextField TXTPhone;
    private javax.swing.JButton UpdateBut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
