/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserAdmin;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import stokbarangpddj.ToolAndClass.Conn;
import stokbarangpddj.MenuUtama;
import stokbarangpddj.ToolAndClass.AllClass;
import stokbarangpddj.ToolAndClass.NumberRenderer;
import stokbarangpddj.ToolAndClass.Tools;

/**
 *
 * @author admin
 */
public class AdminUser extends javax.swing.JInternalFrame {
Conn koneksi;
ResultSet resultSet;
Statement statement;
String userLogin = "";
    /**
     * Creates new form AdminUser
     */
    public AdminUser() {
        initComponents();
        //Conn.setConnection();
        updateTable();
    }
    
    public void updateTable(){
                DefaultTableModel Table = (DefaultTableModel) TableUser.getModel();
                while(Table.getRowCount() > 0) Table.removeRow(0);
                TableColumnModel CTable = TableUser.getColumnModel();
                CTable.getColumn(4).setCellRenderer(NumberRenderer.getDateTimeRenderer());
		try {
			Conn.rowSet.setCommand("select idusername, Name, username, telephone, date_join from user");
			Conn.rowSet.execute();
                        while(Conn.rowSet.next())
                        {
                            Table.addRow(new Object[]{Conn.rowSet.getString(1),Conn.rowSet.getString(2),Conn.rowSet.getString(3),Conn.rowSet.getString(4),Conn.rowSet.getTimestamp(5)});
                        }
	
		} catch (SQLException ex) {
			Logger.getLogger(AdminUser.class.getName()).log(Level.SEVERE, null, ex);
		}
    }
    
    private void clear(){
        TxTUsername.setText("");
        TxTName.setText("");
        TXTPhone.setText("");
        TxTPassword.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BackBut = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableUser = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        LabelName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxTName = new javax.swing.JTextField();
        TxTUsername = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TXTPhone = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        TxTPassword = new javax.swing.JPasswordField();
        AddBut = new javax.swing.JButton();
        UpdateBut = new javax.swing.JButton();
        DeleteBut = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(900, 597));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Admin Control User", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Adobe Arabic", 1, 14))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(639, 488));

        BackBut.setText("Back");
        BackBut.setMaximumSize(new java.awt.Dimension(51, 23));
        BackBut.setMinimumSize(new java.awt.Dimension(51, 23));
        BackBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButActionPerformed(evt);
            }
        });

        TableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Username", "Telephone", "Date Join"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableUserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableUser);

        jLabel2.setText("Username");

        LabelName.setText("Name");

        jLabel5.setText(":");

        jLabel6.setText(":");

        jLabel9.setText(":");

        jLabel10.setText("Password");

        TXTPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXTPhoneKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTPhoneKeyTyped(evt);
            }
        });

        jLabel11.setText(":");

        jLabel12.setText("Telephone");

        AddBut.setText("Add");
        AddBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButActionPerformed(evt);
            }
        });

        UpdateBut.setText("Update");
        UpdateBut.setMaximumSize(new java.awt.Dimension(51, 23));
        UpdateBut.setMinimumSize(new java.awt.Dimension(51, 23));
        UpdateBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButActionPerformed(evt);
            }
        });

        DeleteBut.setText("Delete");
        DeleteBut.setMaximumSize(new java.awt.Dimension(51, 23));
        DeleteBut.setMinimumSize(new java.awt.Dimension(51, 23));
        DeleteBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BackBut, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                                        .addGap(7, 7, 7)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addGap(18, 18, 18)
                                                .addComponent(TxTPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addGap(18, 18, 18)
                                                .addComponent(TXTPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                            .addComponent(LabelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addComponent(jLabel6)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(TxTName, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TxTUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                                .addComponent(AddBut, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UpdateBut, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DeleteBut, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DeleteBut, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelName)
                            .addComponent(jLabel5)
                            .addComponent(TxTName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(TxTUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(TxTPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(AddBut, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateBut, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BackBut, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TableUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableUserMouseClicked
        // TODO add your handling code here:
        int baris = TableUser.getSelectedRow();
        TxTName.setText(TableUser.getValueAt(baris, 1).toString());
        TxTUsername.setText(TableUser.getValueAt(baris, 2).toString());
        TXTPhone.setText(TableUser.getValueAt(baris, 3).toString());
        TxTPassword.setText("");
    }//GEN-LAST:event_TableUserMouseClicked

    private void BackButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButActionPerformed
        MenuUtama MenuUtama = new MenuUtama();
        Tools.change(this, MenuUtama);
        // TODO add your handling code here:
    }//GEN-LAST:event_BackButActionPerformed

    private void AddButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButActionPerformed
    if(TxTName.getText().isEmpty() == true || TxTUsername.getText().isEmpty() == true || TxTPassword.getText().isEmpty() == true || TXTPhone.getText().isEmpty() == true)
    {
        JOptionPane.showMessageDialog(null, "Please Fill Up All The Gaps","Attention",JOptionPane.ERROR_MESSAGE);
    }
    else
    {
        try {
                // TODO add your handling code here:
                String IDGenerate = AllClass.GenerateID("user", "idusername");
                Conn.rowSet.setCommand("select * from user");
                Conn.rowSet.execute();
                Conn.rowSet.moveToInsertRow();
                Conn.rowSet.updateString("idusername", IDGenerate);
                Conn.rowSet.updateString("username", TxTUsername.getText());
                Conn.rowSet.updateString("password", Tools.MD5Encrypt(TxTPassword.getText()));
                Conn.rowSet.updateString("name", TxTName.getText());
                Conn.rowSet.updateString("telephone", TXTPhone.getText());
                Conn.rowSet.updateTimestamp("date_join", new Timestamp(System.currentTimeMillis()));
                Conn.rowSet.insertRow();
                updateTable();
        } catch (SQLException ex) {
                Logger.getLogger(AdminUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        clear();
        // TODO add your handling code here:
    }//GEN-LAST:event_AddButActionPerformed

    private void TXTPhoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTPhoneKeyReleased
    if(TXTPhone.getText().isEmpty() == false)
    {
        if(Tools.isNumeric(TXTPhone.getText())==false)
        {
            JOptionPane.showMessageDialog(null, "Not Valid Input!!","ERROR!!",JOptionPane.ERROR_MESSAGE);
            TXTPhone.setText("");
        }
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTPhoneKeyReleased

    private void TXTPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTPhoneKeyTyped
    if(TXTPhone.getText().length() > 12)
        {
             JOptionPane.showMessageDialog(null, "Please Insert Correct Phone!! - Max 12","Attention",JOptionPane.ERROR_MESSAGE);
             TXTPhone.setText("");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTPhoneKeyTyped

    private void UpdateButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButActionPerformed
    if(TxTName.getText().isEmpty() == true || TxTUsername.getText().isEmpty() == true || TxTPassword.getText().isEmpty() == true || TXTPhone.getText().isEmpty() == true)
        {
            JOptionPane.showMessageDialog(null, "Please Fill Up All The Gaps\nOr Select The Table","Attention",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            try{
                int baris = TableUser.getSelectedRow();
                Conn.rowSet.setCommand("select * from user");
                Conn.rowSet.execute();
                Conn.rowSet.absolute(baris+1);
                Conn.rowSet.updateString("username", TxTUsername.getText());
                Conn.rowSet.updateString("name", TxTName.getText());
                Conn.rowSet.updateString("telephone", TXTPhone.getText());
                Conn.rowSet.updateRow();
                updateTable();
                } catch (SQLException ex) {
                Logger.getLogger(AdminUser.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        clear();
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateButActionPerformed

    private void DeleteButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButActionPerformed
    if(TxTName.getText().isEmpty() == true || TxTUsername.getText().isEmpty() == true || TxTPassword.getText().isEmpty() == true || TXTPhone.getText().isEmpty() == true)
        {
            JOptionPane.showMessageDialog(null, "Please Fill Up All The Gaps\nOr Select The Table","Attention",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            try {
            int baris = TableUser.getSelectedRow();
            Conn.rowSet.setCommand("select * from user");
            Conn.rowSet.execute();
            Conn.rowSet.absolute(baris+1);
            Conn.rowSet.deleteRow();
            updateTable();
            } catch (SQLException ex) {
                    Logger.getLogger(AdminUser.class.getName()).log(Level.SEVERE, null, ex);
//                    JOptionPane.showMessageDialog(null, "Please Delete All Inventory With this Category First!!","ERROR!!",JOptionPane.ERROR_MESSAGE);
            }
        }
        clear();   
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteButActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBut;
    private javax.swing.JButton BackBut;
    private javax.swing.JButton DeleteBut;
    private javax.swing.JLabel LabelName;
    private javax.swing.JTextField TXTPhone;
    private javax.swing.JTable TableUser;
    private javax.swing.JTextField TxTName;
    private javax.swing.JPasswordField TxTPassword;
    private javax.swing.JTextField TxTUsername;
    private javax.swing.JButton UpdateBut;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
