/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package stokbarangpddj;

import stokbarangpddj.ToolAndClass.Conn;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.io.InputStream;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import stokbarangpddj.ToolAndClass.AllClass;
import stokbarangpddj.ToolAndClass.RunningTextActionListener;

/**
 *
 * @author Susanto
 */
public class Login extends javax.swing.JInternalFrame {
        public static int kondisiLogin=-1;
	public static String userID;//Hilangkan angka 1 
	public static String userLogin = "";
        Timer timer; 
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        makeCenter();
        Conn.setConnection();
        timer = new Timer(100, new RunningTextActionListener(LBLRUN));
        timer.start();
    }

    
    private void makeCenter(){
              Dimension desktopSize = Toolkit.getDefaultToolkit().getScreenSize();
              Dimension jInternalFrameSize = this.getSize();
              this.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
              (desktopSize.height- jInternalFrameSize.height)/2);
    }
    
    
    
   private void prosesLogin() {
       try {			
			String sql = "select * from user where username ='" + txtUsername.getText() +"' AND password = md5('"+ txtPassword.getText() +"')";
			Conn.rowSet.setCommand(sql);
			Conn.rowSet.execute();

			while (Conn.rowSet.next()) {
				userID = Conn.rowSet.getString("idusername");
				userLogin = Conn.rowSet.getString("Name");
			}
			if (userLogin.equals("")) {
				JOptionPane.showMessageDialog(null, "USERNAME atau PASSWORD SALAH","ERROR!!",JOptionPane.ERROR_MESSAGE);
				clear();
                                LogLogin("Failed");
			} 
			else {
                                    LogLogin("Sukses");
                                    MenuUtama frm = new MenuUtama();
                                    FrameUtama.DekstopFrame.add(frm);
                                    frm.setVisible(true);
                                    frm.setMaximum(true);
                                    dispose();
                                    FrameUtama.UserStat.setText("Welcome, " + userLogin);
			}
//                        Conn.rowSet.close();
       } catch (Exception  e) {
           Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, e);
       }
   }
    
    private void LogLogin(String Status) throws SQLException{
//                try {
//                    String Ip = AllClass.GetIpPublic();
                    String Ip = "192";
                    String logs = "select idlog, username, ip_log, status, date from log"; 
                    Conn.rowSet.setCommand(logs);
                    Conn.rowSet.execute();
                    Conn.rowSet.moveToInsertRow();
                    Conn.rowSet.updateString("Username", txtUsername.getText());
                    Conn.rowSet.updateTimestamp("date", new Timestamp(System.currentTimeMillis()));
                    Conn.rowSet.updateString("ip_log", Ip);
                    Conn.rowSet.updateString("status", Status);
                    Conn.rowSet.insertRow();
//                    Conn.rowSet.close();
//                } catch (IOException ex) {
//                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
//                } 
    }
    
    void clear(){
        txtUsername.setText("");
        txtPassword.setText("");
    }
    
    public void loadimage(){
        try
        {
            Conn.rowSet.setCommand("select * from store");
            Conn.rowSet.execute();
            while (Conn.rowSet.next()) {
                InputStream is = Conn.rowSet.getBinaryStream("Logo");
                Image bimg = ImageIO.read(is);
                bimg = bimg.getScaledInstance(285,124,Image.SCALE_SMOOTH);
                ImageIcon icon = new ImageIcon(bimg);
                ImageLogo.setIcon(icon);
            }
//            Conn.rowSet.close();
        }   catch(Exception e){
         e.printStackTrace();
        }}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        ImageLogoPanel = new javax.swing.JPanel();
        ImageLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        CancelButton = new javax.swing.JButton();
        LoginButton = new javax.swing.JButton();
        LBLRUN = new javax.swing.JLabel();

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Adobe Arabic", 1, 14), java.awt.Color.red)); // NOI18N

        ImageLogoPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout ImageLogoPanelLayout = new javax.swing.GroupLayout(ImageLogoPanel);
        ImageLogoPanel.setLayout(ImageLogoPanelLayout);
        ImageLogoPanelLayout.setHorizontalGroup(
            ImageLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImageLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
        );
        ImageLogoPanelLayout.setVerticalGroup(
            ImageLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImageLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
        );

        jLabel1.setText("Username :");

        jLabel2.setText("Password  :");

        txtUsername.setText("1");

        txtPassword.setText("1");
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        LBLRUN.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        LBLRUN.setForeground(new java.awt.Color(255, 51, 51));
        LBLRUN.setText("                                                                                    PD.DIAN JAYA Inventory App Beta V 1.0");
        LBLRUN.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                LBLRUNMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ImageLogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsername)
                    .addComponent(txtPassword)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(CancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(LBLRUN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(LBLRUN, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CancelButton)
                            .addComponent(LoginButton)))
                    .addComponent(ImageLogoPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        prosesLogin();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        System.exit(0);
            try {
                Conn.rowSet.close();
                // TODO add your handling code here:
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        prosesLogin();
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void LBLRUNMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBLRUNMouseMoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_LBLRUNMouseMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel ImageLogo;
    private javax.swing.JPanel ImageLogoPanel;
    private javax.swing.JLabel LBLRUN;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
