/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Inventory;

import java.awt.Dimension;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import stokbarangpddj.ToolAndClass.Conn;
import stokbarangpddj.MenuUtama;
import stokbarangpddj.ToolAndClass.AllClass;
import stokbarangpddj.ToolAndClass.Tools;

/**
 *
 * @author Susanto
 */
public class Category extends javax.swing.JInternalFrame {

    /**
     * Creates new form Category
     */
    public Category() {
        initComponents();
        updateTable();
        makeCenter();
    }
    
    public void updateTable(){
		try {
                        DefaultTableModel Tabel = (DefaultTableModel) TableCat.getModel();
                        while(Tabel.getRowCount() > 0) Tabel.removeRow(0);
			Conn.rowSet.setCommand("select * from category");
			Conn.rowSet.execute();
                        while(Conn.rowSet.next())
                        {
                            Tabel.addRow(new Object[]{Conn.rowSet.getString("idCategory"),Conn.rowSet.getString("Name")});
                        }
		} catch (SQLException ex) {
			Logger.getLogger(Category.class.getName()).log(Level.SEVERE, null, ex);
		}
    }
    
    private void clear(){
        TXTName.setText("");
        LabelID.setText("ID AUTO GENERATE");
    }
    
    private void makeCenter() {
		Dimension frameSize = this.getSize();
		if (frameSize.height > 594) {
			frameSize.height = 594;
		}
		if (frameSize.width > 900) {
			frameSize.width = 900;
		}
		this.setLocation((900 - frameSize.width) / 2, (594 - frameSize.height) / 2);
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TXTName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableCat = new javax.swing.JTable();
        DeleteCat = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        LabelID = new javax.swing.JLabel();
        UpdateCat = new javax.swing.JButton();
        AddCat = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BackCat = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Category", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel1.setText("Nama Category");

        TableCat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name"
            }
        ));
        TableCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableCatMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableCat);

        DeleteCat.setText("Delete");
        DeleteCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteCatActionPerformed(evt);
            }
        });

        jLabel2.setText("ID");

        LabelID.setText("ID AUTO GENERATE");

        UpdateCat.setText("Update");
        UpdateCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateCatActionPerformed(evt);
            }
        });

        AddCat.setText("Add");
        AddCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCatActionPerformed(evt);
            }
        });

        jLabel3.setText(":");

        jLabel4.setText(":");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TXTName)
                            .addComponent(LabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddCat, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UpdateCat, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeleteCat, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelID)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXTName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AddCat, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(UpdateCat, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DeleteCat, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                .addContainerGap())
        );

        BackCat.setText("Back");
        BackCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackCatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BackCat, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BackCat, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCatActionPerformed
    if(TXTName.getText().isEmpty() == true)
    {
        JOptionPane.showMessageDialog(null, "Your Data Is Not Complete!!");
    }
    else
    {
                    try {
                            String GenerateIDCat = AllClass.GenerateID("category", "idCategory");
                            // TODO add your handling code here:
                            Conn.rowSet.setCommand("select * from category");
                            Conn.rowSet.execute();
                            Conn.rowSet.moveToInsertRow();
                            Conn.rowSet.updateString("idCategory", GenerateIDCat);
                            Conn.rowSet.updateString("Name", TXTName.getText());
                            Conn.rowSet.insertRow();
                            updateTable();
                    } catch (SQLException ex) {
                            Logger.getLogger(Category.class.getName()).log(Level.SEVERE, null, ex);
                    }
    }
        clear();
        // TODO add your handling code here:
    }//GEN-LAST:event_AddCatActionPerformed

    private void TableCatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableCatMouseClicked
        int baris = TableCat.getSelectedRow();
        LabelID.setText(TableCat.getValueAt(baris, 0).toString());
        TXTName.setText(TableCat.getValueAt(baris, 1).toString());
        // TODO add your handling code here:
    }//GEN-LAST:event_TableCatMouseClicked

    private void UpdateCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateCatActionPerformed
    if(TXTName.getText().isEmpty() == true)
    {
        JOptionPane.showMessageDialog(null, "Please Select Your Data First!!");
    }
    else
    {
            try{
                int baris = TableCat.getSelectedRow();
                Conn.rowSet.setCommand("select * from category");
                Conn.rowSet.execute();
                Conn.rowSet.absolute(baris+1);
//                Conn.rowSet.updateString("idCategory", LabelID.getText());
                Conn.rowSet.updateString("Name", TXTName.getText());
                Conn.rowSet.updateRow();
                updateTable();
                } catch (SQLException ex) {
                Logger.getLogger(Category.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
                clear();
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateCatActionPerformed

    private void DeleteCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteCatActionPerformed
        if(TXTName.getText().isEmpty() == true)
        {
            JOptionPane.showMessageDialog(null, "Please Select Your Data First!!");
        }
        else
        {
        try {
        // TODO add your handling code here:
        int baris = TableCat.getSelectedRow();
        Conn.rowSet.setCommand("select * from category");
        Conn.rowSet.execute();
        Conn.rowSet.absolute(baris+1);
        Conn.rowSet.deleteRow();
        updateTable();
        } catch (SQLException ex) {
                Logger.getLogger(Category.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Please Delete All Inventory With this Category First!!","ERROR!!",JOptionPane.ERROR_MESSAGE);
        }
        }
        clear();
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteCatActionPerformed

    private void BackCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackCatActionPerformed
        MenuUtama MenuUtama = new MenuUtama();
        Tools.change(this, MenuUtama);
        // TODO add your handling code here:
    }//GEN-LAST:event_BackCatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCat;
    private javax.swing.JButton BackCat;
    private javax.swing.JButton DeleteCat;
    private javax.swing.JLabel LabelID;
    private javax.swing.JTextField TXTName;
    private javax.swing.JTable TableCat;
    private javax.swing.JButton UpdateCat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
